### ISSUE TITLE
Abandoned project?

### ISSUE THREAD

**Issue by wuniversales** [Daniel-Griffiths/vapour#100]
Has the Project been abandoned?
I see that since 2019 it has not been updated and it seems very strange to me.
In case the project has been abandoned, can you tell me an alternative that receives updates?

**Comment by Ohrwerk** [comment]
Looks like it, too bad actually.

**Comment by Ohrwerk** [comment]
very very very sad, especially now that the new client has become so unusable. At the moment, only the compact mode is actually usable.

**Comment by Daniel-Griffiths** [comment]
Suprise! I just uploaded a 2.0 version using the latest version of Electron, it should work as expected now.
