### ISSUE TITLE
Installing games?

### ISSUE THREAD

**Issue by FireBotBurnss** [Daniel-Griffiths/vapour#102]
How do i install games when i click them on the home screen it asks me to get an app to open the steam link please help.

**Comment by Ohrwerk** [comment]
This alternative Steam client has not been updated for years and is no longer usable.
If you no longer like the current Steam client, you only have two options,
either you buy DRM-free games from another provider where no client is required,
or you try a rollback of the Steam client with which you can at least install your games
and play them in offline mode.
I don't know if this still works, I haven't been online with the client for a long time.

HowTo for rollback the StreamClient:
https://blog.lightwo.net/steam-client-downgrades-survival-kit.html

Client version I use if i need it (Version 30.05.2023):
steam.exe -forcesteamupdate -forcepackagedownload -overridepackageurl http://web.archive.org/web/20230531113527if_/media.steampowered.com/client -exitsteam

Good Luck

**Comment by Daniel-Griffiths** [comment]
Suprise! I just uploaded a 2.0 version using the latest version of Electron, it should work as expected now.

Let me know if you have any issues.
